### PR TITLE
Resolve htmlproofer failures in CI

### PR DESCRIPTION
**Pull request by jonafato**
Update URLs to use https instead of http

This is a bulk update to resolve almost all of the htmlproofer CI errors
(and generally to link to secure versions of websites). The remaining 7
errors reported by htmlproofer are conference-specific and relate to the
inability to validate links via libcurl, which may be due to servers not
supporting https or domains no longer resolving.

---

Update websites for a batch of conferences

These updates fall into two categories:

1. Websites of inactive conferences that no longer exist or no longer
   contain conference-related content. In these instances, I've updated
   the links to the latest relevant snapshots I could find on the
   Internet Archive.

2. Conferences whose canonical domains (as referenced by their websites
   or social media accounts) do not match the domains used here
   currently.

The last remaining htmlproofer error regards PyCon UK, whose canonical
domain is correctly listed here, but it does not respond to https
requests, and so I've reverted it back to http in this commit. This
ensures that the link is still usable but does not resolve the CI error
regarding http links.

### CODE REVIEW

**Comment by jefftriplett** [comment]
I think linking to the https://2023.pyconuk.org website would be the most appropriate given all options.

**Comment by jonafato** [comment]
> I think linking to the https://2023.pyconuk.org website would be the most appropriate given all options.

:white_check_mark:

**Review by jefftriplett — APPROVED** [review]

**Comment by jefftriplett** [comment]
@jonafato I was wrong. I don't have permission to re-run an action or to merge one. Otherwise, I'd merge this since it should pass in theory.

**Comment by glasnt** [comment]
The HTML Proofer section of the checks are now passing. There are separate issues with the Netlify checks that I am addressing in #72. 

Because this is a major update to the data on the site, I'd prefer to wait until the Netlify fix is in, then rebase this PR to ensure that works before merging.

**Comment by glasnt** [comment]
For some reason, as a maintainer I cannot rebase this PR to get Netlify to run with the new configurations, and I cannot push a noop commit to make Netlify re-run this check. Manually retrying Netlify from that interface uses the older configurations. 

@jonafato This PR needs to be manually rebased to force netlify to re-try with the new configurations from #72

**Comment by glasnt** [comment]
Netlify is working 🥳 

Just 3 htmlproof errors left

**Comment by jonafato** [comment]
These errors are not present on my local build and were just timeouts. I've pushed once more to re-trigger the build, which as now passed. If this job continues to be flaky, I'll look into configuring the timeout on these checks. In particular, these seemed to be failing on archive.org links, and it wouldn't surprise me to see an infrequently accessed archive of a conference website respond slowly.

**Comment by glasnt** [comment]
All checks currently green, so will merge ✅

**Pull request merged**
