### PR TITLE
Added PyCon Uganda

### PR DESCRIPTION
**Pull request by HassanBahati**
Added PyCon Uganda to `_national` directory.

### CODE REVIEW

**Comment by HassanBahati** [comment]
@glasnt @malemburg  , 
i did commit to a [my fork of this repository](https://github.com/HassanBahati/pycon.org) and it deploys a preview at [this url ](https://hassanbahati.github.io/pycon.org/) 

the netlify deploy on the other hand  here seems to fail, from an [inspection ](https://app.netlify.com/sites/pycon-dot-org/deploys/66b111fd901b580008be100c) seems there is a compatibility issue 
```
8:55:33 PM: ffi-1.17.0-x86_64-linux-musl requires rubygems version >= 3.3.22, which is
8:55:33 PM: incompatible with the current version, 3.0.8
```
image

from what i see online such as below, there seem to be a couple recommendations;  
1. https://github.com/orgs/community/discussions/127006 posted on june 2nd 2024
2. https://github.com/ffi/ffi/issues/1103 posted on june 3rd 2024

**Comment by glasnt** [comment]
Thanks for this investigation, @HassanBahati! I'll correct these dependencies in another PR, then rebase this one.

**Comment by glasnt** [comment]
The htmlproofer checks are erroring for other reasons, but these changes work!

**Comment by HassanBahati** [comment]
> Thanks for this investigation, @HassanBahati! I'll correct these dependencies in another PR, then rebase this one.

its a pleasure @glasnt, thank you!

**Pull request merged**
