### PR TITLE
Update DjangoCon US location to "rotating"

### PR DESCRIPTION
**Pull request by jonafato**
DjangoCon US is an event that changes location within the US. This change updates the listed location similar to two other events listed here.

### CODE REVIEW

**Review by jefftriplett — APPROVED** [review]
Accurate!

**Comment by jonafato** [comment]
I think it would also make sense to move this to the "national" category.

**Comment by glasnt** [comment]
👍 to adding "(rotating)" (matches PyCon APAC, PyCon Africa)

😕  to moving it to National, as it's a special interest event (only because it's a _django_ con, not a _py_ con.

**Comment by jonafato** [comment]
> 😕 to moving it to National, as it's a special interest event (only because it's a django con, not a py con.

Makes sense. I was looking at the project's `_national` vs. `_regional` directories rather than the "& Special Interest" qualifier on the page. i.e. it is a national event, just not a general Python one.

**Pull request merged**
